20240804/rails/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"

  post "upload_file" => "welcome#upload_file", as: :custom_upload_file

  resources :attachments
end

20240804/rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

20240804/rails/app/models/attachment.rb
class Attachment < ApplicationRecord
end

20240804/rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

20240804/rails/app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  before_action :set_attachment, only: %i[show edit update destroy]

  # GET /attachments or /attachments.json
  def index
    @attachments = Attachment.all
  end

  # GET /attachments/1 or /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments or /attachments.json
  def create
    uploaded_file = attachment_params[:uploaded_file]

    if uploaded_file.nil?
      raise ActiveRecord::RecordInvalid.new(Attachment.new)
    end

    @attachment = Attachment.new(
      original_filename: uploaded_file.original_filename,
      content_type: uploaded_file.content_type,
      size: uploaded_file.size,
      body: Base64.encode64(uploaded_file.read)
    )
    @attachment.save!

    respond_to do |format|
      format.html { redirect_to attachment_url(@attachment), notice: "Attachment was successfully created." }
      format.json { render :show, status: :created, location: @attachment }
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.html { render :new, status: :unprocessable_entity }
      format.json { render json: @attachment.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /attachments/1 or /attachments/1.json
  def update
    uploaded_file = attachment_params[:uploaded_file]

    if uploaded_file.nil?
      raise ActiveRecord::RecordInvalid.new(Attachment.new)
    end

    @attachment.update!(
      original_filename: uploaded_file.original_filename,
      content_type: uploaded_file.content_type,
      size: uploaded_file.size,
      body: Base64.encode64(uploaded_file.read)
    )

    respond_to do |format|
      format.html { redirect_to attachment_url(@attachment), notice: "Attachment was successfully updated." }
      format.json { render :show, status: :ok, location: @attachment }
    end
  rescue ActiveRecord::RecordInvalid
    respond_to do |format|
      format.html { render :edit, status: :unprocessable_entity }
      format.json { render json: @attachment.errors, status: :unprocessable_entity }
    end
  end

  # DELETE /attachments/1 or /attachments/1.json
  def destroy
    @attachment.destroy!

    respond_to do |format|
      format.html { redirect_to attachments_url, notice: "Attachment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attachment_params
      params.require(:attachment).permit(:uploaded_file)
    end
end

20240804/rails/app/controllers/welcome_controller.rb
require 'httparty'

class WelcomeController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
  end

  def upload_file
    uploaded_file = params[:file]

    response = HTTParty.post(
      'http://localhost:3000/attachments',
      # Use `multipart: true` to send files. But it's just optional.
      # multipart: true,
      body: {
        attachment: {
          # Don't use `uploaded_file.tempfile` here!
          uploaded_file: uploaded_file
        }
      }
    )

    render json: {
      ok: response.ok?,
      code: response.code,
      data: response
    }
  end
end

20240804/rails/app/helpers/application_helper.rb
module ApplicationHelper
end

20240804/rails/app/helpers/attachments_helper.rb
module AttachmentsHelper
end

20240804/rails/app/views/attachments/_attachment.html.erb
<div id="<%= dom_id attachment %>">
  <p>
    <strong>Original filename:</strong>
    <%= attachment.original_filename %>
  </p>
  <p>
    <strong>Content type:</strong>
    <%= attachment.content_type %>
  </p>
  <p>
    <strong>Size:</strong>
    <%= number_with_delimiter attachment.size %>
  </p>
  <p>
    <strong>Body:</strong>
    <%= image_tag("data:#{attachment.content_type};base64, #{attachment.body}", width: '400') %>
  </p>
</div>

20240804/rails/app/views/attachments/_form.html.erb
<%= form_with(model: attachment) do |form| %>
  <% if attachment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attachment.errors.count, "error") %> prohibited this attachment from being saved:</h2>
      <ul>
        <% attachment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :uploaded_file %>
    <%= form.file_field :uploaded_file %>
  </p>
  <div>
    <%= form.submit 'Upload' %>
  </div>
<% end %>

20240804/rails/app/views/attachments/edit.html.erb
<h1>Editing attachment</h1>

<%= render "form", attachment: @attachment %>

<br>

<div>
  <%= link_to "Show this attachment", @attachment %> |
  <%= link_to "Back to attachments", attachments_path %>
</div>

20240804/rails/app/views/attachments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attachments</h1>

<div id="attachments">
  <% @attachments.each do |attachment| %>
    <%= render attachment %>
    <p>
      <%= link_to "Show this attachment", attachment %>
    </p>
  <% end %>
</div>

<%= link_to "New attachment", new_attachment_path %>

20240804/rails/app/views/attachments/new.html.erb
<h1>New attachment</h1>

<%= render "form", attachment: @attachment %>

<br>

<div>
  <%= link_to "Back to attachments", attachments_path %>
</div>

20240804/rails/app/views/attachments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attachment %>

<div>
  <%= link_to "Edit this attachment", edit_attachment_path(@attachment) %> |
  <%= link_to "Back to attachments", attachments_path %>

  <%= button_to "Destroy this attachment", @attachment, method: :delete %>
</div>

20240804/rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
      <h1><%= link_to "Demo", root_path %></h1>
      <nav>
        <ul>
          <li>
            <%= link_to "Home", root_path %>
          </li>
          <li>
            <%= link_to "Attachments", attachments_path %>
          </li>
        </ul>
      </nav>
      <hr />
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

20240804/rails/app/views/welcome/index.html.erb
<form action="<%= custom_upload_file_path %>" method="post" enctype="multipart/form-data">
  <h2>Upload Attachment</h2>
  <p>
    <label for="attachment_file">File:</label>
    <input type="file" name="file" id="attachment_file" />
  </p>
  <p>
    <input type="submit" value="Upload" />
  </p>
</form>